import type { OrdersPayload } from './types';

export function getOrdersPayload(): OrdersPayload {
  return {
    header: {
      title: 'Orders Hub',
      description: 'Manage pickup, delivery, and shipped orders across all channels.',
    },
    syncBadges: [
      { label: 'Meadow sync: Live', variant: 'live' },
      { label: 'Flower Co.: Connected', variant: 'connected' },
    ],
    filterCounts: { pending: 4 },
    orders: [
      {
        id: 'ORD-0091',
        time: '2m ago',
        customer: 'Sarah Jenkins',
        email: 'sarah.j@email.com',
        type: 'Pickup',
        source: 'Meadow POS',
        store: 'Hollywood',
        total: '$145.00',
        status: 'Pending',
        statusType: 'warning',
      },
      {
        id: 'ORD-0090',
        time: '15m ago',
        customer: 'Marcus Cole',
        email: 'mcole42@email.com',
        type: 'Delivery',
        source: 'Flower Co. Partner',
        deliveryPartner: 'Flower Co. — Channel Partner',
        store: 'Downtown',
        total: '$89.50',
        status: 'In Transit',
        statusType: 'default',
      },
      {
        id: 'ORD-0089',
        time: '1h ago',
        customer: 'Elena Rodriguez',
        email: 'elena.r@email.com',
        type: 'Pickup',
        source: 'Meadow POS',
        store: 'Venice',
        total: '$210.00',
        status: 'Completed',
        statusType: 'success',
      },
      {
        id: 'ORD-0088',
        time: '1h 12m ago',
        customer: 'David Kim',
        email: 'dkim99@email.com',
        type: 'Delivery',
        source: 'CŪPR Direct',
        store: 'Hollywood',
        total: '$315.00',
        status: 'Failed: ID Verification',
        statusType: 'destructive',
      },
      {
        id: 'ORD-0087',
        time: '2h ago',
        customer: 'Guest User',
        email: '--',
        type: 'Pickup',
        source: 'Google Business',
        store: 'Santa Monica',
        total: '$65.00',
        status: 'Completed',
        statusType: 'success',
      },
      {
        id: 'ORD-0086',
        time: '2h 30m ago',
        customer: 'Jordan Lee',
        email: 'jordanlee12@email.com',
        type: 'Pickup',
        source: 'CŪPR Direct',
        store: 'Hollywood',
        total: '$180.00',
        status: 'Pending',
        statusType: 'warning',
      },
    ],
  };
}
